---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whoogle

labels:
  - includeSelectors: true
    pairs:
      app: whoogle

resources:
  - ../../base
  - certificate.yaml
  - ingress.yaml

configMapGenerator:
  - name: whoogle-env
    behavior: replace
    files:
      - config/whoogle.env
    